Made filter configuration file. Added set methods.
nikolaydymura/native_filters pull request #6
Opened 2022-09-26 10:54 UTC by EgorEko

2022-09-26 11:03 UTC, nikolaydymura requested changes

2022-09-26 11:03 UTC, nikolaydymura commented on lib/factory/filter_configuration_builder.dart
> +  void setInt(String key, num value) {
Use int here

2022-09-26 11:03 UTC, nikolaydymura commented on lib/factory/filter_configuration_builder.dart
> +  void setNSValue(String key, dynamic value) {
Change to List<double>

2022-09-26 11:03 UTC, nikolaydymura commented on lib/factory/filter_configuration_builder.dart
> +  void setPoint(String key, Point value) {
Change to Point<num>

2022-09-26 12:50 UTC, EgorEko commented on lib/factory/filter_configuration_builder.dart
> +  void setBool(String key, num value) {
Changed to bool

2022-09-26 12:51 UTC, EgorEko commented on lib/factory/filter_configuration_builder.dart
> +  void setCIVector(String key, CIVector value) {
Changed to List<double>

2022-09-26 12:53 UTC, EgorEko commented on lib/factory/filter_configuration_builder.dart
> +  void setNSValue(String key, dynamic value) {
Changed to List<double>

2022-09-26 12:57 UTC, EgorEko commented on lib/factory/filter_configuration_builder.dart
> +  void setInt(String key, num value) {
Changed to int

2022-09-27 13:34 UTC, nikolaydymura approved these changes

2022-09-27 13:35 UTC, merged